routes/web.php
Route::get('/diary/food_diary', function() 
{ 
    return view('diary.food_diary');    
}
);

/*
* Diary
*/
//  Route::get('/diary/{schedule_id}/{auth_token}', ['uses'=>'UserController@LoginAndRedirectDiaryQuestions']);

Route::group(['prefix'=>'dashboard', 'as'=>'dashboard.', 'middleware'=>'auth'], function(){
	
// Route::get('/user/edit', ['uses'=>'UserController@edit', 'as'=>'user.edit']);
// Route::post('/user/edit', ['uses'=>'UserController@editStore', 'as'=>'user.edit']);

//conetnts
// Route::get('/study/{study_id}/content', ['uses'=>'DashboardController@contents', 'as'=>'study.contents']);
// Route::get('/contents', ['uses'=>'DashboardController@contents', 'as'=>'contents']);
// Route::get('/study/{study_id}/content/add', ['uses'=>'DashboardController@Addcontents', 'as'=>'study.contents.add']);
// Route::Post('/study/content/add', ['uses'=>'DashboardController@storecontents', 'as'=>'store.contents']);
// Route::get('/study/{study_id}/content/{content_id}/Editcontent', ['uses'=>'DashboardController@Editcontent', 'as'=>'study.Editcontent']);
// Route::Post('/study/content/urls', ['uses'=>'DashboardController@urls', 'as'=>'store.urls']);
// Route::get('/study/{study_id}/content/add/url', ['uses'=>'DashboardController@AddUrlcontents', 'as'=>'study.contents.add.url']);
// Route::post('/study/postcontentsurl', ['uses'=>'DashboardController@postcontentsurl', 'as'=>'study.postcontentsurl']);
// Route::post('/study/postcontentcalculator', ['uses'=>'DashboardController@postcontentcalculator', 'as'=>'study.postcontentcalculator']);
// Route::post('/study/Postupdatecontent', ['uses'=>'DashboardController@Postupdatecontent', 'as'=>'content.Postupdatecontent']);
// Route::get('/study/{study_id}/content/calculator', ['uses'=>'DashboardController@Calculatorcontents', 'as'=>'study.contents.calculator']);
// Route::get('/study/{study_id}/content/document', ['uses'=>'DashboardController@Documentcontents', 'as'=>'study.contents.document']);
// Route::get('/study/{study_id}/content/solutions', ['uses'=>'DashboardController@Solutioncontents', 'as'=>'study.contents.solutions']);
// // Route::post('/study/getstudies', ['uses'=>'DashboardController@getstudies', 'as'=>'study.getstudies']);
// // Route::get('/study/getstudiesss', ['uses'=>'DashboardController@getstudiesss', 'as'=>'study.getstudiesss']);
// Route::get('/study/{study_id}/content/{content_id}/addrevision', ['uses'=>'DashboardController@addrevisioncontent', 'as'=>'study.addrevision']);
// Route::Post('/study/postrevision', ['uses'=>'DashboardController@postrevision', 'as'=>'study.postrevision']);
// Route::get('/study/{study_id}/content/{content_id}/viewrevision', ['uses'=>'DashboardController@viewrevisioncontent', 'as'=>'study.viewrevision']);




//diary dashboard

// Route::get('/study/{study_id}/diarydashboard', ['uses'=>'DashboardController@diarydashboard', 'as'=>'study.diarydashboard']);

Route::get('/patient/{patient_id}/study/{study_id}/aswerdiaries', ['uses'=>'DashboardController@aswerdiaries', 'as'=>'answerdiaries']);
Route::get('/patient/{patient_id}/study/{study_id}/missingdiaries', ['uses'=>'DashboardController@missingdiaries', 'as'=>'missingdiaries']);
Route::get('/patient/{patient_id}/study/{study_id}/shecdulediaries', ['uses'=>'DashboardController@shecdulediaries', 'as'=>'shecdulediaries']);

// Schedule
Route::get('/study/{study_id}/studyschedule', ['uses'=>'StudyController@studyschedule', 'as'=>'study.studyschedule']);
Route::get('/study/{study_id}/CreateSchedule', ['uses'=>'StudyController@CreateSchedule', 'as'=>'study.CreateSchedule']);
Route::get('/study/{study_id}/StudyScheduleExport', ['uses'=>'StudyController@StudyScheduleExport', 'as'=>'study.StudyScheduleExport']);

Route::get('/CronSchedule', ['uses'=>'DashboardController@CronSchedule', 'as'=>'CronSchedule']);
Route::get('/CronCheckUsersRegistered', ['uses'=>'DashboardController@CronCheckUsersRegistered', 'as'=>'CronCheckUsersRegistered']);

Route::get("addVisits","VisitScheduleController@createVisitSchedule");
Route::post("addVisits","VisitScheduleConroller@createVisitSchedulePost")->name('createvisitschedulepost');


//end



/**
 * Sites
 */
Route::get('/study/{study_id}/ViewSites', ['uses'=>'SiteController@ViewSites', 'as'=>'site.ViewSites']);
Route::get('/study/{study_id}/CreateNewSite', ['uses'=>'SiteController@CreateNewSite', 'as'=>'site.CreateNewSite']);
Route::post('/study/PostNewSite', ['uses'=>'SiteController@PostNewSite', 'as'=>'site.PostNewSite']);
Route::get('/study/{study_id}/site/{site_id}/editsite', ['uses'=>'SiteController@editsite', 'as'=>'editsite']);
Route::post('/study/updatesite', ['uses'=>'SiteController@updatesite', 'as'=>'updatesite']);






/**
 * Users
 */
// Route::get('/study/{study_id}/ViewUsers', ['uses'=>'UserController@ViewUsers', 'as'=>'user.ViewUsers']);
// Route::get('/study/{study_id}/CreateNewUser', ['uses'=>'UserController@CreateNewUser', 'as'=>'user.CreateNewUser']);
Route::post('/study/PostNewUser', ['uses'=>'UserController@PostNewUser', 'as'=>'user.PostNewUser']);
Route::get('/study/{study_id}/site/{site_id}/Registeruserbysite', ['uses'=>'UserController@Registeruserbysite', 'as'=>'Registeruserbysite']);
Route::get('/study/{study_id}/site/{site_id}/ViewUser', ['uses'=>'UserController@Viewuserbysite', 'as'=>'Viewuserbysite']);
Route::get('/study/{study_id}/user/{user_id}/edituser', ['uses'=>'UserController@edituser', 'as'=>'edituser']);
Route::post('/study/updateuser', ['uses'=>'UserController@updateuser', 'as'=>'updateuser']);

// Route::get('/study/{study_id}/user/{user_id}/status/{is_activate}/updateuserstatus', ['uses'=>'UserController@updateuserstatus', 'as'=>'updateuserstatus']);


/**
 * StudyDocuments
 */


// Route::get('/study/{study_id}/StudyDocuments', ['uses'=>'StudyController@GetStudyDocuments', 'as'=>'study.StudyDocuments']);
// Route::get('/study/{study_id}/CreateStudyDocuments', ['uses'=>'StudyController@CreateStudyDocuments', 'as'=>'study.CreateStudyDocuments']);
// Route::post('/study//StoreStudyDocuments', ['uses'=>'StudyController@StoreStudyDocuments', 'as'=>'study.StoreStudyDocuments']);
// Route::get('/study/{study_id}/document/{id}/EditStudyDocuments', ['uses'=>'StudyController@EditStudyDocuments', 'as'=>'study.EditStudyDocuments']);
// Route::post('/study/UpdateStudyDocuments', ['uses'=>'StudyController@UpdateStudyDocuments', 'as'=>'study.UpdateStudyDocuments']);


/**
 * Organizations
 */
// Route::get('/Organizations', ['uses'=>'OrganizationsController@ViewOrganizations', 'as'=>'Organizations']);
Route::get('/Organizations/Create', ['uses'=>'OrganizationsController@CreateOrganization', 'as'=>'CreateOrganization']);
Route::Post('/study/AddOrganization', ['uses'=>'OrganizationsController@AddOrganization', 'as'=>'AddOrganization']);	
Route::get('/EditOrganization/{id}', ['uses'=>'OrganizationsController@EditOrganization', 'as'=>'EditOrganization']);
Route::Post('/Organizations/Update', ['uses'=>'OrganizationsController@UpdateOrganization', 'as'=>'UpdateOrganization']);
Route::Post('/Organizations/relatestudy', ['uses'=>'OrganizationsController@relatestudy', 'as'=>'relatestudy']);
Route::get('/Organizations/{id}/addsite', ['uses'=>'OrganizationsController@addsite', 'as'=>'addsite']);
Route::post('/Organizations/postsite', ['uses'=>'OrganizationsController@postsite', 'as'=>'postsite']);
Route::get('/Organizations/{id}/viewsite', ['uses'=>'OrganizationsController@viewsite', 'as'=>'viewsite']);	

/**
 * Studies
 */
//  Route::get('/Studies', ['uses'=>'StudiesController@ViewStudies', 'as'=>'Studies']);
//  Route::get('/Studies/Create', ['uses'=>'StudiesController@CreateStudy', 'as'=>'CreateStudy']);
//  Route::Post('/AddStudy', ['uses'=>'StudiesController@AddStudy', 'as'=>'AddStudy']);
//  Route::get('/EditStudy/{id}', ['uses'=>'StudiesController@EditStudy', 'as'=>'EditStudy']);
//  Route::Post('/Studies/Update', ['uses'=>'StudiesController@UpdateStudy', 'as'=>'UpdateStudy']);
// // Route::get('/', ['uses'=>'DashboardController@index', 'as'=>'index']);
// Route::get('/diary-page/{diary_type}', ['uses'=>'DashboardController@diaryPage', 'as'=>'diaryPage']);
// Route::post('/save-study', ['uses'=>'DashboardController@saveStudy', 'as'=>'save-study']);
// Route::get('/logout', ['uses'=>'UserController@logout', 'as'=>'logout']);


/**
* Study
*/
// Route::get('/study/{id}/chart/{workflow_id}/forms', ['uses'=>'StudyController@showChartForms', 'as'=>'showChartForms']);
// Route::get('/study/{id}/chart', ['uses'=>'StudyController@showChart', 'as'=>'showChart']);
// Route::get('/study/{id}/{language}', ['uses'=>'StudyController@show', 'as'=>'study']);
Route::get('/study//export/{study_id}', ['uses'=>'StudyController@exportPatientsList', 'as'=>'study.exportPatients']);
// Route::get('/site/{site_id}/{study_id}', ['uses'=>'StudyController@showSite', 'as'=>'site.show']);
/**
* Diary
*/
Route::post('/diary/save/answers', ['uses'=>'DiaryController@saveAnswers']);
Route::get('/diary/{schedule_id}', ['uses'=>'DiaryController@getDiaryQuestions'])->name('diary_questions');
Route::get('/diary/confirm/diary/{schedule_id}', ['uses'=>'DiaryController@confirmDiary'])->name('confirm-diary');
// Route::get('/diary/incomplete/{study_id}/all/{site_id?}', ['uses'=>'DiaryController@incompleteDiary', 'as'=>'incompleteDiary']);
/**
* Patients
*/
Route::group(['prefix'=>'patient', 'as'=>'patient.'], function() {
Route::get('/register', ['uses'=>'PatientsController@register', 'as'=>'register']);
Route::post('/register', ['uses'=>'PatientsController@registerStore', 'as'=>'register']);
Route::post('/get-languages-and-site-nbr/{study_id}', ['uses'=>'PatientsController@getLanguagesAndSiteNbr', 'as'=>'get-languages']);
Route::post('/save-visit-date', ['uses'=>'PatientsController@SaveVisitDate', 'as'=>'save-visit-date']);
Route::get('/list', ['uses'=>'PatientsController@patientsList', 'as'=>'list']);
Route::get('/export-patients-list/{site_id?}/{study_id?}', ['uses'=>'PatientsController@exportPatientsList', 'as'=>'export-patients-list']);

resources/views/studyschedule/createVisitSchedule.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Laravel - Dynamically Add or Remove input fields using JQuery</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />  
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>  
    <meta name="csrf-token" content="{{ csrf_token() }}">
</head>
<body>


<div class="container">
    <h2 align="center">Laravel - Dynamically Add or Remove input fields using JQuery</h2>  
    <div class="form-group">
         <form name="add_name" id="add_name">  


            <div class="alert alert-danger print-error-msg" style="display:none">
            <ul></ul>
            </div>


            <div class="alert alert-success print-success-msg" style="display:none">
            <ul></ul>
            </div>


            <div class="table-responsive">  
                <table class="table table-bordered" id="dynamic_field">  
                    <tr>  
                        <td><input type="text" name="name[]" placeholder="Enter your Name" class="form-control name_list" /></td>  
                        <td><button type="button" name="add" id="add" class="btn btn-success">Add More</button></td>  
                    </tr>  
                </table>  
                <input type="button" name="submit" id="submit" class="btn btn-info" value="Submit" />  
            </div>


         </form>  
    </div> 
</div>


<script type="text/javascript">
    $(document).ready(function(){      
      var postURL = "<?php echo url('addmore'); ?>";
      var i=1;  


      $('#add').click(function(){  
           i++;  
           $('#dynamic_field').append('<tr id="row'+i+'" class="dynamic-added"><td><input type="text" name="name[]" placeholder="Enter your Name" class="form-control name_list" /></td><td><button type="button" name="remove" id="'+i+'" class="btn btn-danger btn_remove">X</button></td></tr>');  
      });  


      $(document).on('click', '.btn_remove', function(){  
           var button_id = $(this).attr("id");   
           $('#row'+button_id+'').remove();  
      });  


      $.ajaxSetup({
          headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
          }
      });


      $('#submit').click(function(){            
           $.ajax({  
                url:postURL,  
                method:"POST",  
                data:$('#add_name').serialize(),
                type:'json',
                success:function(data)  
                {
                    if(data.error){
                        printErrorMsg(data.error);
                    }else{
                        i=1;
                        $('.dynamic-added').remove();
                        $('#add_name')[0].reset();
                        $(".print-success-msg").find("ul").html('');
                        $(".print-success-msg").css('display','block');
                        $(".print-error-msg").css('display','none');
                        $(".print-success-msg").find("ul").append('<li>Record Inserted Successfully.</li>');
                    }
                }  
           });  
      });  


      function printErrorMsg (msg) {
         $(".print-error-msg").find("ul").html('');
         $(".print-error-msg").css('display','block');
         $(".print-success-msg").css('display','none');
         $.each( msg, function( key, value ) {
            $(".print-error-msg").find("ul").append('<li>'+value+'</li>');
         });
      }
    });  
</script>
</body>
</html>

resources/views/studyschedule/index.blade.php
@extends('layouts.site')
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />  
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script> 
@section('content')
@if(!empty(Cookie::get('user_role')) && (int)Cookie::get('user_role')!==1)
  <?php $Study=$study_id;?>
<div class="col col-lg-12">
	<nav aria-label="breadcrumb">
       <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ route('home')}}">Home</a></li>    
        <li class="breadcrumb-item active" aria-current="page">
		<a href="{{ route('dashboard.study', [$study_id,'English']) }}" >{{$response->study_name->study_name}}</a></li>
		<li class="breadcrumb-item" aria-current="page">Study Schedule</li>
		</ol>
	</nav>
    <div class="card">
             <div class="card-block">
		<h5 class="card-title mb-4 pull-left">Study Schedule</h5>
			
			   <a class="btn btn-primary pull-right"  href="{{ route('dashboard.study.StudyScheduleExport', $study_id) }}"><i class="fa fa-file-excel-o"></i> Overview Report</a>
			  <div class="table-responsive" >
                  <table  class="table table-striped table-bordered" cellspacing="0" width="100%">
                       
                        <form method="POST" id="visit_schedule" >
						    <div class="alert alert-danger print-error-msg" style="display:none">
				            <ul></ul>
				            </div>
				
				
				            <div class="alert alert-success print-success-msg" style="display:none">
				            <ul></ul>
				            </div>
			                 <table class="table table-bordered table-striped" id="dynamic_field">
			               <thead>
	                        <tr class="text-primary">
	                            <th>Visit Name</th>
	                            <th>Low Target</th>
	                            <th>Target</th>
	                            <th>High Target</th>
	                        </tr>
			               </thead>
			               <tbody>
			
			               </tbody>
			               <tfoot>
			                <tr>
	                            <td><input type="text" name="visit_name[]" placeholder="Enter Visit Name" class="form-control name_list" /></td>  
	                            <td><input type="text" name="low_target[]" placeholder="Enter Low Target" class="form-control name_list" /></td>  
	                            <td><input type="text" name="target[]" placeholder="Enter Visit Target" class="form-control name_list" /></td>  
	                            <td><input type="text" name="high_target[]" placeholder="Enter High Target" class="form-control name_list" /></td>  
								<td><button type="button" name="add" id="add" class="btn btn-success">Add More</button></td>
			                 
			                 
			                </tr>
			               </tfoot>
			           </table>
			            @csrf
			                  <input type="submit" name="save" id="save" class="btn btn-primary" value="Save" />
						</form>
                       
                        <?php 
	                        
	                       // dd($response);
	                       // die();
	                       //{{ route("createvisitschedulepost") }}
	                       ?>
                       
            </table>
        </div>
    </div>
</div>
   
</div>


@endif
@endsection

<script type="text/javascript">
    $(document).ready(function(){      
      var postURL = "<?php echo url('addmore'); ?>";
      var i=1;  


      $('#add').click(function(){  
           i++;  
           $('#dynamic_field').append('<tr id="row'+i+'" class="dynamic-added"><td><input type="text" name="visit_name[]" placeholder="Enter your Name" class="form-control name_list" /></td><td><input type="text" name="low_target[]" placeholder="Enter your Name" class="form-control name_list" /></td><td><input type="text" name="target[]" placeholder="Enter your Name" class="form-control name_list" /></td><td><input type="text" name="high_target[]" placeholder="Enter your Name" class="form-control name_list" /></td><td><button type="button" name="remove" id="'+i+'" class="btn btn-danger btn_remove">X</button></td></tr>');  
      });  


      $(document).on('click', '.btn_remove', function(){  
           var button_id = $(this).attr("id");   
           $('#row'+button_id+'').remove();  
      });  


      $.ajaxSetup({
          headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
          }
      });


      $('#submit').click(function(){            
           $.ajax({  
                url:postURL,  
                method:"POST",  
                data:$('#add_name').serialize(),
                type:'json',
                success:function(data)  
                {
                    if(data.error){
                        printErrorMsg(data.error);
                    }else{
                        i=1;
                        $('.dynamic-added').remove();
                        $('#add_name')[0].reset();
                        $(".print-success-msg").find("ul").html('');
                        $(".print-success-msg").css('display','block');
                        $(".print-error-msg").css('display','none');
                        $(".print-success-msg").find("ul").append('<li>Record Inserted Successfully.</li>');
                    }
                }  
           });  
      });  


      function printErrorMsg (msg) {
         $(".print-error-msg").find("ul").html('');
         $(".print-error-msg").css('display','block');
         $(".print-success-msg").css('display','none');
         $.each( msg, function( key, value ) {
            $(".print-error-msg").find("ul").append('<li>'+value+'</li>');
         });
      }
    });  
</script>

resources/views/studyschedule/studyschedule_export.blade.php
<table>
    <thead>
    <tr>
        <th>Subject</th>
                            <th>Baseline</th>
                            <th>Text 1</th>
                            <th>Days from baseline</th>
                            <th>Text 2</th>
							<th>Days from last text</th>
                           				 <th>Text 3</th>
							<th>Days from last text</th>
							  <th>Text 4</th>
							<th>Days from last text</th>
                            				<th>Text 5</th>
							<th>Days from last text</th>
							  <th>Text 6</th>
							<th>Days from last text</th>
                           				 <th>Text 7</th>
							<th>Days from last text</th>
							<th>Text 8</th>
							<th>Days from last text</th>
							  <th>Text 9</th>
							<th>Days from last text</th>
                            				<th>Text 10</th>
							<th>Days from last text</th>
							<th>Text 11</th>
							<th>Days from last text</th>

							<th>Text 12</th>
							<th>Days from last text</th>
							<th>Text 13</th>
							<th>Days from last text</th>

							<th>Text 14</th>
							<th>Days from last text</th>
							<th>Text 15</th>
							<th>Days from last text</th>
							<th>Text 16</th>
							<th>Days from last text</th>
							<th>Text 17</th>
							<th>Days from last text</th>

							<th>Text 18</th>
							<th>Days from last text</th>
							<th>Text 19</th>
							<th>Days from last text</th>

							<th>Text 20</th>
							<th>Days from last text</th>
							<th>Text 21</th>
							<th>Days from last text</th>
							<th>Text 22</th>
							<th>Days from last text</th>
							<th>Text 23</th>
							<th>Days from last text</th>
							<th>Text 24</th>
							<th>Days from last text</th>
							<th>Text 25</th>
							<th>Days from last text</th>





    </tr>
    </thead>
    <tbody>
       @foreach($data->StudyOverView as $datas)
				<tr>		
				<td>{{$datas->patient_nbr}}</td>
                                <td>{{$datas->enrollment_date}}</td>
				<?php $previous =null;  ?>	

			@foreach($data->DiarySchedule as $diary)

	                @if($diary->patient_id ==$datas->patient_id)


						
				<td>{{$diary->created_at}}</td>
                                
			<?php	
	    	   	 if ($previous !== null) {        
	 $difference= strtotime($diary->created_at)-strtotime($previous);
        echo "<td>".floor($difference/(60*60*24))."</td>";     	}

   	 $previous = $diary->created_at; 
    	?>
		
                     
				
								
              @endif
			 @endforeach
			</tr>

          @endforeach

    </tbody>
</table>

resources/views/studyschedule/visitschedule.blade.php
@extends('layouts.site')

@section('content')

<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

   				

@section('content')
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />  
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script> 
    
<div class="container">
    <h2 align="center">Create Visit Schedule</h2>  
    <div class="form-group">
         <form name="add_name" id="add_name">  


            <div class="alert alert-danger print-error-msg" style="display:none">
            <ul></ul>
            </div>


            <div class="alert alert-success print-success-msg" style="display:none">
            <ul></ul>
            </div>


            <div class="table-responsive">  
                <table class="table table-bordered" id="dynamic_field">  
                    <tr>  
                        <td><input type="text" name="visitname[]" placeholder="Enter Visit Name" class="form-control name_list" /></td> 
                        <td><input type="text" name="lowtarget[]" placeholder="Enter Low Target Number" class="form-control name_list" /></td>
                        <td><input type="text" name="target[]" placeholder="Enter Target Number" class="form-control name_list" /></td>
                        <td><input type="text" name="hightarget[]" placeholder="Enter High Target Number" class="form-control name_list" /></td>  
                        <td><button type="button" name="add" id="add" class="btn btn-success">Add More</button></td>  
                    </tr>  
                </table>  
                <input type="button" name="submit" id="submit" class="btn btn-info" value="Submit" />  
            </div>


         </form>  
    </div> 
</div>

<script type="text/javascript">
    $(document).ready(function(){      
      var postURL = "<?php echo url('addmore'); ?>";
      var i=1;  


      $('#add').click(function(){  
           i++;  
           $('#dynamic_field').append('<tr id="row'+i+'" class="dynamic-added"><td><input type="text" name="visitname[]" placeholder="Enter Visit Name" class="form-control name_list" /></td><td><input type="text" name="lowtarget[]" placeholder="Enter Low Target Number" class="form-control name_list" /></td><td><input type="text" name="target[]" placeholder="Enter Target Number" class="form-control name_list" /></td><td><input type="text" name="hightarget[]" placeholder="Enter High Target Number" class="form-control name_list" /></td><td><button type="button" name="remove" id="'+i+'" class="btn btn-danger btn_remove">X</button></td></tr>');  
      });  


      $(document).on('click', '.btn_remove', function(){  
           var button_id = $(this).attr("id");   
           $('#row'+button_id+'').remove();  
      });  


      $.ajaxSetup({
          headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
          }
      });


      $('#submit').click(function(){            
           $.ajax({  
                url:postURL,  
                method:"POST",  
                data:$('#add_name').serialize(),
                type:'json',
                success:function(data)  
                {
                    if(data.error){
                        printErrorMsg(data.error);
                    }else{
                        i=1;
                        $('.dynamic-added').remove();
                        $('#add_name')[0].reset();
                        $(".print-success-msg").find("ul").html('');
                        $(".print-success-msg").css('display','block');
                        $(".print-error-msg").css('display','none');
                        $(".print-success-msg").find("ul").append('<li>Record Inserted Successfully.</li>');
                    }
                }  
           });  
      });  


      function printErrorMsg (msg) {
         $(".print-error-msg").find("ul").html('');
         $(".print-error-msg").css('display','block');
         $(".print-success-msg").css('display','none');
         $.each( msg, function( key, value ) {
            $(".print-error-msg").find("ul").append('<li>'+value+'</li>');
         });
      }
    });  
</script>
@stop

resources/views/studyschedule/xml.blade.php
@extends('layouts.site')

@section('content')
@if(!empty(Cookie::get('user_role')) && (int)Cookie::get('user_role')!==1)
  <?php $Study=$study_id;?>

<?xml version="1.0" encoding="UTF-8"?>
<xs:element name="startdate" type="xs:dateTime"/>
@foreach($response->patientinfo as $data)



@foreach($response->DiarySchedule as $diary)
@if($diary->patient_id === $data->patient_id)
<startdate>{{$data->patient_nbr}}</startdate><br>
<startdate>{{$diary->created_at}}</startdate><br>

  @endif
 @endforeach
 @endforeach








@endif
@endsection